TOPK_RESTAURANTS: 2
TOPK_REVIEWS: 3
BERT_MODEL_NAME: "TASB"
USER_INTENTS_CLASSIFIER: "MultilabelUserIntentsClassifier"
PATH_TO_RESTAURANT_METADATA: "information_retrievers/data/All-Edmonton-Restaurants/top_all_restaurants_sorted.csv"
PATH_TO_RESTAURANT_REVIEW_EMBEDDINGS: "information_retrievers/data/All-Edmonton-Restaurants/large_files/top_all_restaurants_review_embedding_sorted.csv"
PATH_TO_RESTAURANT_REVIEW_EMBEDDING_MATRIX: "information_retrievers/data/All-Edmonton-Restaurants/large_files/matrix.pt"
PATH_TO_NUM_OF_REVIEWS_PER_RESTAURANT: "information_retrievers/data/All-Edmonton-Restaurants/item.pt"
DEFAULT_MAX_DISTANCE_IN_KM: 2
DISTANCE_TYPE: "geodesic"
FILTER_CONSTRAINTS:
  ["location", "cuisine dish type", "already recommended restaurant"]
NUM_REVIEWS_TO_RETURN: 3
GEOCODING_METHOD: "GoogleV3"
DEFAULT_LOCATION: None
ALL_CONSTRAINTS:
  [
    "location",
    "cuisine type",
    "dish type",
    "type of meal",
    "price range",
    "wait times",
    "atmosphere",
    "dietary restrictions",
    "others",
  ]
CONSTRAINTS_UPDATER: "one_step_constraints_updater"
MANDATORY_CONSTRAINTS: [["location"], ["cuisine type", "dish type"]]
CUMULATIVE_CONSTRAINTS:
  [
    "dish type",
    "type of meal",
    "price range",
    "wait times",
    "atmosphere",
    "dietary restrictions",
    "others",
  ]
SPECIFIC_LOCATION_REQUIRED: True
INTENT_PROMPTS_PATH: "prompt_files/user_intent_prompts"
INQUIRE_PROMPT_FILENAME: "inquire_prompt.jinja"
PROVIDE_PREFERENCE_PROMPT_FILENAME: "provide_preference_prompt.jinja"
ASK_FOR_RECOMMENDATION_PROMPT_FILENAME: "ask_for_recommendation_prompt.jinja"
ACCEPT_RECOMMENDATION_PROMPT_FILENAME: "accept_recommendation_prompt.jinja"
REJECT_RECOMMENDATION_PROMPT_FILENAME: "reject_recommendation_prompt.jinja"
RECOMMENDATION_RATING_PROMPT_FILENAME: "recommendation_rating_prompt.jinja"
RECOMMEND_PROMPTS_PATH: "prompt_files/recaction_prompts/recommend_prompts"
CONVERT_STATE_TO_QUERY_PROMPT_FILENAME: "convert_state_to_query_prompt.jinja"
EXPLAIN_RECOMMENDATION_PROMPT_FILENAME: "explain_recommendation_prompt.jinja"
FORMAT_RECOMMENDATION_PROMPT_FILENAME: "format_recommendation_prompt.jinja"
NO_MATCHING_RESTAURANT_PROMPT_FILENAME: "no_matching_restaurant_prompt.jinja"
SUMMARIZE_REVIEW_PROMPT_FILENAME: "summarize_review_prompt.jinja"
ENABLE_LOCATION_MERGE: True
ENABLE_CONSTRAINTS_REMOVAL: True

CONSTRAINTS_PROMPT_PATH: "prompt_files/constraints_prompts"
ONE_STEP_CONSTRAINTS_UPDATER_PROMPT_FILENAME: "one_step_constraints_updater_prompt.jinja"
CONSTRAINTS_EXTRACTOR_PROMPT_FILENAME: "constraints_extractor_prompt.jinja"
CONSTRAINTS_CLASSIFIER_PROMPT_FILENAME: "constraints_classifier_prompt.jinja"
CONSTRAINTS_REMOVER_PROMPT_FILENAME: "constraints_remover_prompt.jinja"
CONSTRAINTS_REMOVE_CHECK_PROMPT_FILENAME: "constraints_remove_check_prompt.jinja"
RESTAURANTS_EXTRACTOR_PROMPT_PATH: "prompt_files/restaurants_extractor_prompts"
ACCEPTED_RESTAURANTS_EXTRACTOR_PROMPT_FILENAME: "accepted_restaurants_extractor_prompt.jinja"
REJECTED_RESTAURANTS_EXTRACTOR_PROMPT_FILENAME: "rejected_restaurants_extractor_prompt.jinja"

ANSWER_PROMPTS_PATH: "prompt_files/recaction_prompts/answer_prompts"
ANSWER_VERIFY_METADATA_RESP_PROMPT: "verify_metadata_resp_prompt.jinja"
ANSWER_FORMAT_MULTIPLE_RESP_PROMPT: "format_multiple_resp_prompt.jinja"
ANSWER_EXTRACT_CATEGORY_PROMPT: "extract_category_prompt.jinja"
ANSWER_HOURS_PROMPT: "hours_prompt.jinja"
ANSWER_ATTR_PROMPT: "attribute_prompt.jinja"
ANSWER_IR_PROMPT: "ir_prompt.jinja"
ANSWER_MULT_QS_PROMPT: "seperate_questions_prompt.jinja"
ANSWER_GPT_PROMPT: "gpt_prompt.jinja"
ANSWER_MULT_QS_FORMAT_RESP_PROMPT: "format_mult_qs_prompt.jinja"

GENERAL_CONFIG_FILE: "restaurant_configs/general_config.csv"
CONSTRAINTS_CONFIG_FILE: "restaurant_configs/constraints_config.csv"
CONSTRAINTS_UPDATER_FEWSHOTS_FILE: "restaurant_configs/constraints_updater_fewshots.csv"