TOPK_ITEMS: 2
TOPK_REVIEWS: 3
IR_BERT_MODEL_NAME: "TASB"
NUM_REVIEWS_TO_RETURN: 3
INTENT_PROMPTS_PATH: "prompt_files/user_intent_prompts"
INQUIRE_PROMPT_FILENAME: "inquire_prompt.jinja"
PROVIDE_PREFERENCE_PROMPT_FILENAME: "provide_preference_prompt.jinja"
ASK_FOR_RECOMMENDATION_PROMPT_FILENAME: "ask_for_recommendation_prompt.jinja"
ACCEPT_RECOMMENDATION_PROMPT_FILENAME: "accept_recommendation_prompt.jinja"
REJECT_RECOMMENDATION_PROMPT_FILENAME: "reject_recommendation_prompt.jinja"
RECOMMEND_PROMPTS_PATH: "prompt_files/recaction_prompts/recommend_prompts"
CONVERT_STATE_TO_QUERY_PROMPT_FILENAME: "convert_state_to_query_prompt.jinja"
EXPLAIN_RECOMMENDATION_PROMPT_FILENAME: "explain_recommendation_prompt.jinja"
FORMAT_RECOMMENDATION_PROMPT_FILENAME: "format_recommendation_prompt.jinja"
NO_MATCHING_ITEM_PROMPT_FILENAME: "no_matching_item_prompt.jinja"
SUMMARIZE_REVIEW_PROMPT_FILENAME: "summarize_review_prompt.jinja"

CONSTRAINTS_PROMPT_PATH: "prompt_files/constraints_prompts"
ONE_STEP_CONSTRAINTS_UPDATER_PROMPT_FILENAME: "one_step_constraints_updater_prompt.jinja"
ITEMS_EXTRACTOR_PROMPT_PATH: "prompt_files/items_extractor_prompts"
ACCEPTED_ITEMS_EXTRACTOR_PROMPT_FILENAME: "accepted_items_extractor_prompt.jinja"
REJECTED_ITEMS_EXTRACTOR_PROMPT_FILENAME: "rejected_items_extractor_prompt.jinja"
CURRENT_ITEMS_EXTRACTOR_PROMPT_FILENAME: "current_items_extractor_prompt.jinja"

ANSWER_PROMPTS_PATH: "prompt_files/recaction_prompts/answer_prompts"
ANSWER_FORMAT_MULTIPLE_RESP_PROMPT: "format_multiple_resp_prompt.jinja"
ANSWER_EXTRACT_CATEGORY_PROMPT: "extract_category_prompt.jinja"
ANSWER_HOURS_PROMPT: "hours_prompt.jinja"
ANSWER_METADATA_PROMPT: "metadata_prompt.jinja"
ANSWER_IR_PROMPT: "ir_prompt.jinja"
ANSWER_MULT_QS_PROMPT: "seperate_questions_prompt.jinja"
ANSWER_MULT_QS_FORMAT_RESP_PROMPT: "format_mult_qs_prompt.jinja"

PATH_TO_DOMAIN_CONFIGS: "domain_specific/configs/restaurant_configs"
MODEL: "gpt-3.5-turbo"
SEARCH_ENGINE: "vector database"
ENABLE_MULTITHREADING: True
UNACCEPTABLE_SIMILARITY_SCORE_RANGE: 0.5
MAX_NUMBER_SIMILAR_ITEMS: 5
ENABLE_PREFERENCE_ELICITATION: False
