DOMAIN: appliances
CONSTRAINTS_CATEGORIES: "constraints_config.csv"
CONSTRAINTS_UPDATER_FEWSHOTS: "constraints_updater_fewshots.csv"
ACCEPTED_ITEMS_EXTRACTOR_FEWSHOTS_FILE: "accepted_items_extractor_fewshots.csv"
REJECTED_ITEMS_EXTRACTOR_FEWSHOTS_FILE: "rejected_items_extractor_fewshots.csv"