DOMAIN: restaurants
EXPLANATION_METADATA_BLACKLIST:
  [
    "address",
    "city",
    "state",
    "postal_code",
    "latitude",
    "longitude",
    "review_count",
    "is_open",
    "categories",
    "hours",
    "stars",
  ]
INQUIRE_CLASSIFICATION_FEWSHOTS_FILE: "inquire_classification_fewshots.csv"
ACCEPT_CLASSIFICATION_FEWSHOTS_FILE: "accept_classification_fewshots.csv"
REJECT_CLASSIFICATION_FEWSHOTS_FILE: "reject_classification_fewshots.csv"
CONSTRAINTS_CATEGORIES: "constraints_config.csv"
CONSTRAINTS_UPDATER_FEWSHOTS: "constraints_updater_fewshots.csv"
ACCEPTED_ITEMS_EXTRACTOR_FEWSHOTS_FILE: "accepted_items_extractor_fewshots.csv"
REJECTED_ITEMS_EXTRACTOR_FEWSHOTS_FILE: "rejected_items_extractor_fewshots.csv"
CURRENT_ITEMS_EXTRACTOR_FEWSHOTS_FILE: "current_items_extractor_fewshots.csv"
ANSWER_EXTRACT_CATEGORY_FEWSHOTS_FILE: "answer_extract_category_fewshots.csv"
ANSWER_IR_FEWSHOTS_FILE: "answer_ir_fewshots.csv"
ANSWER_SEPARATE_QUESTIONS_FEWSHOTS_FILE: "answer_separate_questions_fewshots.csv"
HARD_CODED_RESPONSES_FILE: "hard_coded_responses.csv"
FILTER_CONFIG_FILE: "filter_config.csv"
PATH_TO_ITEM_METADATA: "data/item_metadata.json"
PATH_TO_REVIEWS: "data/items_reviews.csv"
PATH_TO_EMBEDDING_MATRIX: "data/reviews_embedding_matrix.pt"
PATH_TO_DATABASE: "data/database.faiss"
LOCATION_BIAS: "Edmonton"
